### ISSUE TITLE
Change object parameters to variables

### ISSUE THREAD

**Issue by matthewkayne** [Jonathan-0101/tk-toolkit#29]

**Comment by matthewkayne** [comment]
closes #30

**Comment by Jonathan-0101** [comment]
Add edits to example.py file
Remove "self.width = width" and "self.height = height" from the file as they are no longer needed

**Comment by matthewkayne** [comment]
> Add edits to example.py file Remove "self.width = width" and "self.height = height" from the file as they are no longer needed

Done 👍
